### ISSUE TITLE
Pull Requests are not triggering `go mod tidy` and `go mod vendor` checks

### ISSUE THREAD

**Issue by atc0005** [atc0005/todo#51]
## Overview

While reviewing an offered Pull Request for a project that I maintain, I found some of the CI failures to be unclear.

Example:

```
example_constants_test.go:28:10: undeclared name: `nagios` (typecheck)
	os.Exit(nagios.StateOKExitCode)
	        ^
example_constants_test.go:34:3: undeclared name: `nagios` (typecheck)
		nagios.StateOKLabel,
		^
example_constants_test.go:35:3: undeclared name: `nagios` (typecheck)
		nagios.CheckOutputEOL,
		^
Error: Process completed with exit code 1.
```

Looking at other jobs I realized what the real problem was:

```
Run go test -mod=vendor -v ./...
# github.com/atc0005/go-nagios
FAIL	github.com/atc0005/go-nagios [setup failed]
nagios_test.go:6:2: cannot find package "." in:
FAIL
	/__w/go-nagios/go-nagios/vendor/github.com/stretchr/testify/assert
Error: Process completed with exit code 1.
```

The contributor was adding a dependency to the project (`stretchr/testify` for their test cases), but did not vendor the dependency before submitting their PR.

The current CI failures do not indicate that this is expected.

The `go mod tidy` and `go mod vendor` checks are handled here:

```yaml
  go_mod_changes:
    name: Look for uncommitted Go module changes
    runs-on: ubuntu-latest
    timeout-minutes: 10
    container:
      image: ghcr.io/atc0005/go-ci:go-ci-lint-only

    steps:
      - name: Check out code
        uses: actions/checkout@v3.3.0

      - name: go mod tidy
        run: |
          go mod tidy
          git diff --exit-code go.mod

      - name: go mod vendor
        run: |
          go mod vendor
          git diff --exit-code
```

This job is included by importing workflows like this one:

```yaml
name: Push Validation

# Run jobs when someone pushes to a repository branch. This workflow is
# intended to provide quick validation of content changes for Pull Requests
# (new, updated).
on:
  push:

jobs:
  quick_validation:
    name: Quick
    uses: atc0005/shared-project-resources/.github/workflows/quick-validation.yml@master
```

The end result is that these steps *only* run for code pushed to a branch that lives in the project's repo. As I'm the primary contributor to projects that I maintain and am the sole contributor pushing to branches in those repos I didn't catch this "gotcha" until this most recent PR.

I'll plan to either mirror the jobs (duplication), or (more likely) import the `quick-validation.yml` file into another workflow file so that the `go mod tidy` and `go mod vendor` steps run early in the CI jobs process when Pull Requests are submitted.

As of this moment I'm not sure how to pull that off (cleanly) without touching the workflow files in each project (which I was hoping to prevent).

## TODO

Update each project's copy of the `project-analysis.yml` file to include two additional jobs:

```yaml
  go_mod_validation:
    name: Go Module Validation
    uses: atc0005/shared-project-resources/.github/workflows/go-mod-validation.yml@master

  dependency_updates:
    name: Dependency Updates
    uses: atc0005/shared-project-resources/.github/workflows/dependency-updates.yml@master
```

This enables the following steps:

- "Go Module Validation"
  - step: Look for missing go.mod changes
  - step: Look for missing vendored dependencies
- "Dependency Updates"
  - step: Look for available minor or patch releases

By adding these jobs to the existing project-analysis.yml workflow file they're executed on Pull Requests (new, updated) and on the existing weekly schedule.

The expected runtime impact is low.

Along with these changes is the need to update the existing "Branch protection rule" for this project. GH-52 will track that work.

- [x] atc0005/bounce
- [x] atc0005/brick
- [x] atc0005/bridge
- [x] atc0005/check-cert
- [x] atc0005/check-illiad
- [x] atc0005/check-mail
- [x] atc0005/check-ntpt
- [x] atc0005/check-path
- [x] atc0005/check-process
- [x] atc0005/check-restart
- [x] atc0005/check-statuspage
- [x] atc0005/check-vmware
- [x] atc0005/check-whois
- [x] atc0005/dnsc
- [x] atc0005/elbow
- ~atc0005/go-ci~
  - doesn't really apply to this project
- [x] atc0005/go-ezproxy
- [x] atc0005/go-lockss
- [x] atc0005/mysql2sqlite
- [x] atc0005/go-nagios
- [x] atc0005/go-teams-notify
- [x] atc0005/nagios-debug
- [x] atc0005/query-meta
- [x] atc0005/safelinks
- [x] atc0005/send2teams
- [x] atc0005/tsm-pass

## References

- https://github.com/atc0005/shared-project-resources/blob/6e014f254f940c166b899ecb3ccc572a97a0519b/.github/workflows/quick-validation.yml#L38-L57
- https://github.com/atc0005/go-nagios/blob/feba50ddfe7df8d5999ff08c995f7385a97d409e/.github/workflows/push-validation.yml#L8-L19

**Comment by atc0005** [comment]
PRs opened in all applicable projects.

I will need to go back and review the CI results once all jobs complete and merge before closing this GH issue.

**Comment by atc0005** [comment]
> PRs opened in all applicable projects.
> 
> I will need to go back and review the CI results once all jobs complete and merge before closing this GH issue.

Done.
