### ISSUE TITLE
Update `Branch protection rule` entries for all projects

### ISSUE THREAD

**Issue by atc0005** [atc0005/todo#52]
## Overview

As part of the work to resolve #51 I am splitting out the jobs. 

Existing status checks:

- `CI matrix / Lint codebase (go-ci-oldstable, false)`
- `CI matrix / Lint codebase (go-ci-stable, false)`
- `CI matrix / Build codebase (go-ci-oldstable)`
- `CI matrix / Build codebase (go-ci-stable)`
- `CI matrix / Run tests (go-ci-oldstable)`
- `CI matrix / Run tests (go-ci-stable)`
- `Makefile / Lint codebase using Makefile`
- `Quick / Lint and test using latest stable container`
- `Makefile / Build codebase using Makefile all recipe`

These status checks should be removed as they're specific to `push` events, which doesn't apply if someone submits a pull request originating from their fork (which is the normal/expected path):

- actively used
  - `Quick / Lint and test using latest stable container`
- if present (unlikely), remove
  - `Quick / Dependency Updates / Look for available minor or patch releases`
  - `Quick / Go Module Validation / Look for missing go.mod changes`
  - `Quick / Go Module Validation / Look for missing vendored dependencies`

These status checks should be added (required):

- `Go Module Validation / Look for missing go.mod changes`
- `Go Module Validation / Look for missing vendored dependencies`

## TODO

- [x] atc0005/bounce
- [x] atc0005/brick
- [x] atc0005/bridge
- [x] atc0005/check-cert
- [x] atc0005/check-illiad
- [x] atc0005/check-mail
- [x] atc0005/check-ntpt
- [x] atc0005/check-path
- [x] atc0005/check-process
- [x] atc0005/check-restart
- [x] atc0005/check-statuspage
- [x] atc0005/check-vmware
- [x] atc0005/check-whois
- [x] atc0005/dnsc
- [x] atc0005/elbow
- [x] atc0005/go-ci
- [x] atc0005/go-ezproxy
- [x] atc0005/go-lockss
- [x] atc0005/mysql2sqlite
- [x] atc0005/go-nagios
- [x] atc0005/go-teams-notify
- [x] atc0005/nagios-debug
- [x] atc0005/query-meta
- [x] atc0005/safelinks
- [x] atc0005/send2teams
- [x] atc0005/tsm-pass

**Comment by atc0005** [comment]
> * atc0005/go-ci

No real changes to make here (re #51); I reviewed existing settings and nothing problematic stood out.
