### ISSUE TITLE
Surface `plugin.AddPerfData()` error, exit with UNKNOWN exit state

### ISSUE THREAD

**Issue by atc0005** [atc0005/todo#53]
## Overview

[Example ](https://github.com/atc0005/check-restart/blob/13077d86ad023ce1f524bd83f973697fd7b4ba71/cmd/check_reboot/main.go#L109-L114) of code block where the issue is *not* surfaced:

```go
	pd := getPerfData(allAssertions, fileAssertions, registryAssertions)
	if err := plugin.AddPerfData(false, pd...); err != nil {
		log.Error().
			Err(err).
			Msg("failed to add performance data")
	}
```

Until now the approach has been just to log the error and continue. 

At a minimum I believe that I should surface the error by adding to the error collection; an error "collection" is a relatively new feature of the nagios plugin library, so if I had to guess (without checking my memory) I'd say that I opted to log the error vs collecting it as another error (earlier or later) might be more significant and not something that *could* be skipped.

Example of the modified code block:

```go
	pd := getPerfData(allAssertions, fileAssertions, registryAssertions)
	if err := plugin.AddPerfData(false, pd...); err != nil {
		log.Error().
			Err(err).
			Msg("failed to add performance data")

		// Surface the error in plugin output.
		plugin.AddError(err)

		// Abort plugin execution with UNKNOWN status. This should not fail,
		// but if it does, then it's *very* likely a logic bug that should be
		// surfaced.
		plugin.ExitStatusCode = nagios.StateUNKNOWNExitCode
		plugin.ServiceOutput = fmt.Sprintf(
			"%s: Failed to process performance data metrics",
			nagios.StateUNKNOWNLabel,
		)

		return
	}
```

## TODO

Review these projects and apply changes where applicable:

- [x] atc0005/check-cert
- [x] atc0005/check-illiad
- [x] atc0005/check-mail
- [x] atc0005/check-ntpt
- [x] atc0005/check-path
- [x] atc0005/check-process
- [x] atc0005/check-restart
- [x] atc0005/check-statuspage
- [x] atc0005/check-vmware
- [x] atc0005/check-whois
- [x] atc0005/mysql2sqlite
- [x] atc0005/nagios-debug

**Comment by atc0005** [comment]
Example diff from the check-cert project:

```diff
diff --git a/cmd/check_cert/main.go b/cmd/check_cert/main.go
index b119daf..fa13b79 100644
--- a/cmd/check_cert/main.go
+++ b/cmd/check_cert/main.go
@@ -391,7 +391,13 @@ func main() {
 		// Surface the error in plugin output.
 		plugin.AddError(perfDataErr)
 
-		// TODO: Abort plugin execution with UNKNOWN status?
+		plugin.ExitStatusCode = nagios.StateUNKNOWNExitCode
+		plugin.ServiceOutput = fmt.Sprintf(
+			"%s: Failed to generate performance data metrics",
+			nagios.StateUNKNOWNLabel,
+		)
+
+		return
 	}
 
 	if err := plugin.AddPerfData(false, pd...); err != nil {
@@ -402,7 +408,11 @@ func main() {
 		// Surface the error in plugin output.
 		plugin.AddError(err)
 
-		// TODO: Abort plugin execution with UNKNOWN status?
+		plugin.ExitStatusCode = nagios.StateUNKNOWNExitCode
+		plugin.ServiceOutput = fmt.Sprintf(
+			"%s: Failed to process performance data metrics",
+			nagios.StateUNKNOWNLabel,
+		)
 	}
 
 	switch {
```

**Comment by atc0005** [comment]
NOTE: Checking off TODO items if project doesn't currently emit performance data.
