### ISSUE TITLE
Remove `on.push` hook in `Project Analysis` workflow as `CodeQL` no longer requires it to be paired with `on.pull_request`

### ISSUE THREAD

**Issue by atc0005** [atc0005/todo#60]
## Overview

From the v2.3.4 codeql-action [changelog](https://github.com/github/codeql-action/blob/main/CHANGELOG.md):

> Remove the requirement for on.push and on.pull_request to trigger on the same branches. https://github.com/github/codeql-action/pull/1675

## TODO

- [x] atc0005/bounce
- [x] atc0005/brick
- [x] atc0005/bridge
- [x] atc0005/check-cert
- [x] atc0005/check-illiad
- [x] atc0005/check-mail
- [x] atc0005/check-ntpt
- [x] atc0005/check-path
- [x] atc0005/check-process
- [x] atc0005/check-restart
- [x] atc0005/check-statuspage
- [x] atc0005/check-vmware
- [x] atc0005/check-whois
- [x] atc0005/dnsc
- [x] atc0005/elbow
- [x] atc0005/go-ci
- [x] atc0005/go-ezproxy
- [x] atc0005/go-lockss
- [x] atc0005/mysql2sqlite
- [x] atc0005/go-nagios
- [x] atc0005/go-teams-notify
- [x] atc0005/nagios-debug
- [x] atc0005/query-meta
- [x] atc0005/safelinks
- [x] atc0005/send2teams
- [x] atc0005/tsm-pass

## References

- https://github.com/atc0005/todo/issues/56
- https://github.com/github/codeql-action/pull/1675

**Comment by atc0005** [comment]
Tasks complete.
