### ISSUE TITLE
Update all project `Branch protection rules` to replace `Makefile / Build codebase using Makefile all recipe` with `Makefile / Build codebase using Makefile quick recipe`

### ISSUE THREAD

**Issue by atc0005** [atc0005/todo#61]
## Oveview

Most projects importing shared workflows now provide a `quick` Makefile recipe as an alternative to the `all` recipe that I've been using for local/CI build validation thus far.

With recent work in the `atc0005/shared-project-resources` repo I'm now ready to finish swapping the recipes. For any projects lacking a `quick` recipe I can add either a full recipe or an alias to the `all` recipe (e.g., library projects).

## TODO

- [x] atc0005/bounce
- [x] atc0005/brick
- [x] atc0005/bridge
- [x] atc0005/check-cert
- [x] atc0005/check-illiad
- [x] atc0005/check-mail
- [x] atc0005/check-ntpt
- [x] atc0005/check-path
- [x] atc0005/check-process
- [x] atc0005/check-restart
- [x] atc0005/check-statuspage
- [x] atc0005/check-vmware
- [x] atc0005/check-whois
- [x] atc0005/dnsc
- [x] atc0005/elbow
- [x] atc0005/go-ci
- [x] atc0005/go-ezproxy
- [x] atc0005/go-lockss
- [x] atc0005/mysql2sqlite
- [x] atc0005/go-nagios
- [x] atc0005/go-teams-notify
- [x] atc0005/nagios-debug
- [x] atc0005/query-meta
- [x] atc0005/safelinks
- [x] atc0005/send2teams
- [x] atc0005/tsm-pass

## References

- https://github.com/atc0005/shared-project-resources/issues/5
- https://github.com/atc0005/shared-project-resources/issues/47
- https://github.com/atc0005/shared-project-resources/pull/119
- https://github.com/atc0005/shared-project-resources/pull/123

**Comment by atc0005** [comment]
Probably best to do this in waves:

- submit PRs for TODO 60
- remove the `all` build requirement
- add the `quick` build requirement

**Comment by atc0005** [comment]
Tasks complete.
