### ISSUE TITLE
Restore project-specific instance of CodeQL workflow to resolve persistent CodeQL scanning warnings

### ISSUE THREAD

**Issue by atc0005** [atc0005/todo#62]
## Overview

While setting up a new project I noticed that the CodeQL workflow imported via `.github/workflows/project-analysis.yml` failed. It failed hard enough that the entire importing workflow (and all imported flows) failed.

Error:

> The workflow is not valid. .github/workflows/project-analysis.yml (Line: 29, Col: 3): Error calling workflow 'atc0005/shared-project-resources/.github/workflows/vulnerability-analysis.yml@master'. The nested job 'CodeQL' is requesting 'actions: read, security-events: write', but is only allowed 'actions: none, security-events: none'.

CodeQL wasn't setup for the repo, but when I tried to enable it the UI refused to allow me to use the Advanced configuration (based on YAML workflow file) without configuring a new one; the imported workflow was not recognized.

I could choose the `Default` configuration, but this ignored the imported workflow (error above).

I will need to remove the shared `CodeQL` job entry and add project-specific copies of the workflow to work around the idiosyncrasies of this tool.

## TODO

- [x] atc0005/bounce
- [x] atc0005/brick
- [x] atc0005/bridge
- [x] atc0005/check-cert
- [x] atc0005/check-illiad
- [x] atc0005/check-mail
- [x] atc0005/check-ntpt
- [x] atc0005/check-path
- [x] atc0005/check-process
- [x] atc0005/check-restart
- [x] atc0005/check-ssh
- [x] atc0005/check-statuspage
- [x] atc0005/check-vmware
- [x] atc0005/check-whois
- [x] atc0005/dnsc
- [x] atc0005/elbow
- ~atc0005/go-ci~
- [x] atc0005/go-ezproxy
- [x] atc0005/go-lockss
- [x] atc0005/mysql2sqlite
- [x] atc0005/go-nagios
- [x] atc0005/go-teams-notify
- [x] atc0005/nagios-debug
- [x] atc0005/query-meta
- [x] atc0005/safelinks
- [x] atc0005/send2teams
- [x] atc0005/tsm-pass

## References

- https://github.com/atc0005/check-ssh/actions/runs/5254633110/workflow
- https://github.com/atc0005/todo/issues/56
- https://github.com/atc0005/todo/issues/60
