### ISSUE TITLE
Update "optional, leveled logging" section of README files

### ISSUE THREAD

**Issue by atc0005** [atc0005/todo#64]
## Overview

Looks like the output format I indicated in the "template" text I used across project READMEs changed from `JSON` to `logfmt`. There are multiple projects which need to be updated to reflect the correct output format.

## TODO

NOTE: Not all projects listed below may be affected.

- [x] atc0005/check-cert
- [x] atc0005/check-illiad
- [x] atc0005/check-mail
- [x] atc0005/check-ntpt
- [x] atc0005/check-path
- [x] atc0005/check-process
- [x] atc0005/check-restart
- [x] atc0005/check-rsat
- [x] atc0005/check-ssh
- ~atc0005/check-statuspage~
- ~atc0005/check-vmware~
- [x] atc0005/check-whois

## References

- https://brandur.org/logfmt

**Comment by atc0005** [comment]
> * atc0005/check-statuspage

This project currently uses fixed JSON output format for its tooling.

**Comment by atc0005** [comment]
> * atc0005/check-vmware


atc0005/check-statuspage

This project also currently uses fixed JSON output format for its tooling.
