### ISSUE TITLE
Update Go-based projects to Go 1.20 series

### ISSUE THREAD

**Issue by atc0005** [atc0005/todo#68]
## Overview

Update Go-based projects from previous oldstable version (1.19) to latest oldstable version (1.20).

- update Go module version from Go 1.19 to 1.20
- update Dependabot configuration for Dockerfile to ignore Go releases
  outside of the Go 1.20 release series
- update "Canary" Dockerfile to reflect one release back from latest release in Go 1.20 series
  - confirm that Dependabot configuration changes are working as intended

## TODO

- [x] atc0005/bounce
- [x] atc0005/brick
- [x] atc0005/bridge
- [x] atc0005/check-cert
- [x] atc0005/check-illiad
- [x] atc0005/check-mail
- [x] atc0005/check-ntpt
- [x] atc0005/check-path
- [x] atc0005/check-process
- [x] atc0005/check-restart
- [x] atc0005/check-rsat
- [x] atc0005/check-ssh
- [x] atc0005/check-statuspage
- [x] atc0005/check-vmware
- [x] atc0005/check-whois
- [x] atc0005/dnsc
- [x] atc0005/elbow
- [x] atc0005/go-ci
- [x] atc0005/go-ezproxy
- [x] atc0005/go-lockss
- [x] atc0005/go-template
- [x] atc0005/hello-world
- [x] atc0005/mysql2sqlite
- [x] atc0005/go-nagios
- [x] atc0005/go-teams-notify
- [x] atc0005/nagios-debug
- [x] atc0005/query-meta
- [x] atc0005/safelinks
- [x] atc0005/send2teams
- [x] atc0005/tsm-pass

## References

- https://github.com/atc0005/check-vmware/commit/f4d0ca6aeac22e57ddc287652ad438a3c4d3ca1a
- https://github.com/atc0005/check-vmware/pull/710

**Comment by atc0005** [comment]
NOTE: Checking the boxes for library projects (for now). Will hold off updating those until a feature from a newer Go release is needed.
