### ISSUE TITLE
Switch development branch from 1.21 series to specific point release

### ISSUE THREAD

**Issue by atc0005** [atc0005/todo#70]
## Overview

Dependabot recently switched from the 1.21 release candidates to the 1.21 series (and not to a specific point release). This broke the "canary" PR behavior for the development branch.

Update that branch for applicable projects to use the 1.21.0 release in order to switch from a "series" version specifier to a point release. This also confirms that Dependabot monitoring will update from 1.21.0 to 1.21.1 as intended.

## TODO

NOTE: Go ahead and check the box for any non-applicable projects.

- [x] atc0005/brick
- [x] atc0005/bridge
- [x] atc0005/check-cert
- [x] atc0005/check-illiad
- [x] atc0005/check-mail
- [x] atc0005/check-ntpt
- [x] atc0005/check-path
- [x] atc0005/check-process
- [x] atc0005/check-restart
- [x] atc0005/check-rsat
- [x] atc0005/check-ssh
- [x] atc0005/check-statuspage
- [x] atc0005/check-vmware
- [x] atc0005/check-whois
- [x] atc0005/dnsc
- [x] atc0005/elbow
- [x] atc0005/go-ci
- [x] atc0005/go-ezproxy
- [x] atc0005/go-lockss
- [x] atc0005/go-template
- [x] atc0005/hello-world
- [x] atc0005/mysql2sqlite
- [x] atc0005/go-nagios
- [x] atc0005/go-teams-notify
- [x] atc0005/nagios-debug
- [x] atc0005/query-meta
- [x] atc0005/safelinks
- [x] atc0005/send2teams
- [x] atc0005/tsm-pass
